<?php
/**
 * The admin-specific functionality of the plugin.
 *
 * Defines the plugin name, version, and hooks for admin area.
 *
 * @package    WC_Product_Slider
 * @subpackage WC_Product_Slider/Admin
 * @since      1.0.0
 */

namespace WC_Product_Slider\Admin;

/**
 * Admin class
 *
 * Handles all admin-specific functionality including:
 * - Enqueuing admin styles and scripts
 * - Registering meta boxes
 * - Saving post meta data
 *
 * @since 1.0.0
 */
class WC_Product_Slider_Admin {

	/**
	 * The ID of this plugin.
	 *
	 * @since  1.0.0
	 * @access private
	 * @var    string    $plugin_name    The ID of this plugin.
	 */
	private $plugin_name;

	/**
	 * The version of this plugin.
	 *
	 * @since  1.0.0
	 * @access private
	 * @var    string    $version    The current version of this plugin.
	 */
	private $version;

	/**
	 * Initialize the class and set its properties.
	 *
	 * @since 1.0.0
	 * @param string $plugin_name The name of this plugin.
	 * @param string $version     The version of this plugin.
	 */
	public function __construct( $plugin_name, $version ) {
		$this->plugin_name = $plugin_name;
		$this->version     = $version;
	}

	/**
	 * Register the stylesheets for the admin area.
	 *
	 * @since 1.0.0
	 */
	public function enqueue_styles() {
		// Enqueue only on our CPT edit screen.
		$screen = get_current_screen();
		if ( ! $screen || 'wc_product_slider' !== $screen->post_type ) {
			return;
		}

		// Enqueue WordPress components styles.
		wp_enqueue_style( 'wp-components' );

		// Enqueue admin styles built by webpack.
		$admin_css = plugin_dir_url( dirname( __DIR__ ) ) . 'build/admin.css';
		wp_enqueue_style(
			'wc-product-slider-admin',
			$admin_css,
			array( 'wp-components' ),
			$this->version,
			'all'
		);
	}

	/**
	 * Register the JavaScript for the admin area.
	 *
	 * @since 1.0.0
	 */
	public function enqueue_scripts() {
		// Enqueue only on our CPT edit screen.
		$screen = get_current_screen();
		if ( ! $screen || 'wc_product_slider' !== $screen->post_type ) {
			return;
		}

		// Get asset file generated by @wordpress/scripts.
		$asset_file = plugin_dir_path( dirname( __DIR__ ) ) . 'build/admin.asset.php';

		if ( ! file_exists( $asset_file ) ) {
			return;
		}

		$asset = require $asset_file;

		// Enqueue admin script built by webpack.
		$admin_js = plugin_dir_url( dirname( __DIR__ ) ) . 'build/admin.js';
		wp_enqueue_script(
			'wc-product-slider-admin',
			$admin_js,
			$asset['dependencies'],
			$asset['version'],
			true
		);

		// Localize script with WooCommerce REST API configuration.
		wp_localize_script(
			'wc-product-slider-admin',
			'wcProductSlider',
			array(
				'restUrl'   => esc_url_raw( rest_url() ),
				'nonce'     => wp_create_nonce( 'wp_rest' ),
				'ajaxUrl'   => admin_url( 'admin-ajax.php' ),
				'pluginUrl' => plugin_dir_url( dirname( __DIR__ ) ),
			)
		);
	}

	/**
	 * Register meta boxes for slider configuration.
	 *
	 * @since 1.0.0
	 */
	public function add_meta_boxes() {
		add_meta_box(
			'wc_product_slider_products',
			__( 'Products', 'woocommerce-product-slider' ),
			array( $this, 'render_products_meta_box' ),
			'wc_product_slider',
			'normal',
			'high'
		);

		add_meta_box(
			'wc_product_slider_design',
			__( 'Design Settings', 'woocommerce-product-slider' ),
			array( $this, 'render_design_meta_box' ),
			'wc_product_slider',
			'normal',
			'default'
		);

		add_meta_box(
			'wc_product_slider_behavior',
			__( 'Behavior Settings', 'woocommerce-product-slider' ),
			array( $this, 'render_behavior_meta_box' ),
			'wc_product_slider',
			'side',
			'default'
		);

		add_meta_box(
			'wc_product_slider_shortcode',
			__( 'Shortcode', 'woocommerce-product-slider' ),
			array( $this, 'render_shortcode_meta_box' ),
			'wc_product_slider',
			'side',
			'high'
		);

		add_meta_box(
			'wc_product_slider_custom_css',
			__( 'Custom CSS', 'woocommerce-product-slider' ),
			array( $this, 'render_custom_css_meta_box' ),
			'wc_product_slider',
			'normal',
			'low'
		);
	}

	/**
	 * Render products meta box.
	 *
	 * @since 1.0.0
	 * @param \WP_Post $post Current post object.
	 */
	public function render_products_meta_box( $post ) {
		// Add nonce for security.
		wp_nonce_field( 'wc_product_slider_save_products', 'wc_product_slider_products_nonce' );

		// Get saved products.
		$selected_products = get_post_meta( $post->ID, '_wc_ps_products', true );
		if ( ! is_array( $selected_products ) ) {
			$selected_products = array();
		}

		echo '<p>' . esc_html__( 'Select products to display in this slider.', 'woocommerce-product-slider' ) . '</p>';
		echo '<input type="hidden" name="wc_ps_products" id="wc_ps_products" value="' . esc_attr( implode( ',', $selected_products ) ) . '" />';
		echo '<div id="wc-ps-product-selector"></div>';
	}

	/**
	 * Render design meta box.
	 *
	 * @since 1.0.0
	 * @param \WP_Post $post Current post object.
	 */
	public function render_design_meta_box( $post ) {
		wp_nonce_field( 'wc_product_slider_save_design', 'wc_product_slider_design_nonce' );

		$primary_color   = get_post_meta( $post->ID, '_wc_ps_primary_color', true );
		$secondary_color = get_post_meta( $post->ID, '_wc_ps_secondary_color', true );

		if ( empty( $primary_color ) ) {
			$primary_color = '#000000';
		}
		if ( empty( $secondary_color ) ) {
			$secondary_color = '#ffffff';
		}
		?>
		<p>
			<label for="wc_ps_primary_color"><?php esc_html_e( 'Primary Color:', 'woocommerce-product-slider' ); ?></label><br>
			<input type="color" name="wc_ps_primary_color" id="wc_ps_primary_color" value="<?php echo esc_attr( $primary_color ); ?>" />
		</p>
		<p>
			<label for="wc_ps_secondary_color"><?php esc_html_e( 'Secondary Color:', 'woocommerce-product-slider' ); ?></label><br>
			<input type="color" name="wc_ps_secondary_color" id="wc_ps_secondary_color" value="<?php echo esc_attr( $secondary_color ); ?>" />
		</p>
		<?php
	}

	/**
	 * Render behavior meta box.
	 *
	 * @since 1.0.0
	 * @param \WP_Post $post Current post object.
	 */
	public function render_behavior_meta_box( $post ) {
		wp_nonce_field( 'wc_product_slider_save_behavior', 'wc_product_slider_behavior_nonce' );

		$autoplay = get_post_meta( $post->ID, '_wc_ps_autoplay', true );
		$loop     = get_post_meta( $post->ID, '_wc_ps_loop', true );
		$speed    = get_post_meta( $post->ID, '_wc_ps_speed', true );

		if ( empty( $speed ) ) {
			$speed = 3000;
		}
		?>
		<p>
			<label>
				<input type="checkbox" name="wc_ps_autoplay" value="1" <?php checked( $autoplay, '1' ); ?> />
				<?php esc_html_e( 'Enable Autoplay', 'woocommerce-product-slider' ); ?>
			</label>
		</p>
		<p>
			<label>
				<input type="checkbox" name="wc_ps_loop" value="1" <?php checked( $loop, '1' ); ?> />
				<?php esc_html_e( 'Loop Slides', 'woocommerce-product-slider' ); ?>
			</label>
		</p>
		<p>
			<label for="wc_ps_speed"><?php esc_html_e( 'Autoplay Speed (ms):', 'woocommerce-product-slider' ); ?></label><br>
			<input type="number" name="wc_ps_speed" id="wc_ps_speed" value="<?php echo esc_attr( $speed ); ?>" min="1000" max="10000" step="100" />
		</p>
		<?php
	}

	/**
	 * Render shortcode meta box.
	 *
	 * @since 1.0.0
	 * @param \WP_Post $post Current post object.
	 */
	public function render_shortcode_meta_box( $post ) {
		// Only show shortcode for published sliders.
		if ( 'publish' !== $post->post_status ) {
			echo '<p class="description">' . esc_html__( 'Publish this slider to generate a shortcode.', 'woocommerce-product-slider' ) . '</p>';
			return;
		}

		$shortcode = '[wc_product_slider id="' . $post->ID . '"]';
		?>
		<div class="wc-ps-shortcode-container">
			<p class="description">
				<?php esc_html_e( 'Copy and paste this shortcode into any post or page:', 'woocommerce-product-slider' ); ?>
			</p>
			<div class="wc-ps-shortcode-wrapper">
				<input
					type="text"
					readonly
					value="<?php echo esc_attr( $shortcode ); ?>"
					class="wc-ps-shortcode-input"
					id="wc-ps-shortcode-input"
					onclick="this.select();"
				/>
				<button
					type="button"
					class="button button-primary wc-ps-copy-shortcode"
					data-shortcode="<?php echo esc_attr( $shortcode ); ?>"
				>
					<?php esc_html_e( 'Copy', 'woocommerce-product-slider' ); ?>
				</button>
			</div>
			<p class="wc-ps-copy-feedback" style="display:none; color: #46b450; margin-top: 8px;">
				<?php esc_html_e( 'Shortcode copied to clipboard!', 'woocommerce-product-slider' ); ?>
			</p>
		</div>
		<?php
	}

	/**
	 * Render custom CSS meta box.
	 *
	 * @since 1.0.0
	 * @param \WP_Post $post Current post object.
	 */
	public function render_custom_css_meta_box( $post ) {
		wp_nonce_field( 'wc_product_slider_save_custom_css', 'wc_product_slider_custom_css_nonce' );

		$custom_css = get_post_meta( $post->ID, '_wc_ps_custom_css', true );
		if ( ! is_string( $custom_css ) ) {
			$custom_css = '';
		}

		echo '<input type="hidden" name="wc_ps_custom_css" id="wc_ps_custom_css" value="' . esc_attr( $custom_css ) . '" />';
		echo '<div id="wc-ps-css-editor"></div>';
	}

	/**
	 * Save meta box data.
	 *
	 * @since 1.0.0
	 * @param int $post_id Post ID.
	 */
	public function save_meta_box( $post_id ) {
		// Check if this is an autosave.
		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
			return;
		}

		// Check post type.
		if ( ! isset( $_POST['post_type'] ) || 'wc_product_slider' !== $_POST['post_type'] ) {
			return;
		}

		// Check user permissions.
		if ( ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}

		// Save products.
		if ( isset( $_POST['wc_product_slider_products_nonce'] ) &&
			wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['wc_product_slider_products_nonce'] ) ), 'wc_product_slider_save_products' ) ) {

			if ( isset( $_POST['wc_ps_products'] ) ) {
				$products       = sanitize_text_field( wp_unslash( $_POST['wc_ps_products'] ) );
				$products_array = array_filter( array_map( 'absint', explode( ',', $products ) ) );
				update_post_meta( $post_id, '_wc_ps_products', $products_array );
			}
		}

		// Save design settings.
		if ( isset( $_POST['wc_product_slider_design_nonce'] ) &&
			wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['wc_product_slider_design_nonce'] ) ), 'wc_product_slider_save_design' ) ) {

			if ( isset( $_POST['wc_ps_primary_color'] ) ) {
				$primary_color = sanitize_hex_color( wp_unslash( $_POST['wc_ps_primary_color'] ) );
				update_post_meta( $post_id, '_wc_ps_primary_color', $primary_color );
			}

			if ( isset( $_POST['wc_ps_secondary_color'] ) ) {
				$secondary_color = sanitize_hex_color( wp_unslash( $_POST['wc_ps_secondary_color'] ) );
				update_post_meta( $post_id, '_wc_ps_secondary_color', $secondary_color );
			}
		}

		// Save behavior settings.
		if ( isset( $_POST['wc_product_slider_behavior_nonce'] ) &&
			wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['wc_product_slider_behavior_nonce'] ) ), 'wc_product_slider_save_behavior' ) ) {

			$autoplay = isset( $_POST['wc_ps_autoplay'] ) ? '1' : '0';
			update_post_meta( $post_id, '_wc_ps_autoplay', $autoplay );

			$loop = isset( $_POST['wc_ps_loop'] ) ? '1' : '0';
			update_post_meta( $post_id, '_wc_ps_loop', $loop );

			if ( isset( $_POST['wc_ps_speed'] ) ) {
				$speed = absint( $_POST['wc_ps_speed'] );
				update_post_meta( $post_id, '_wc_ps_speed', $speed );
			}
		}

		// Save custom CSS.
		if ( isset( $_POST['wc_product_slider_custom_css_nonce'] ) &&
			wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['wc_product_slider_custom_css_nonce'] ) ), 'wc_product_slider_save_custom_css' ) ) {

			if ( isset( $_POST['wc_ps_custom_css'] ) ) {
				$custom_css = wp_strip_all_tags( wp_unslash( $_POST['wc_ps_custom_css'] ) );
				update_post_meta( $post_id, '_wc_ps_custom_css', $custom_css );
			}
		}
	}

	/**
	 * Add settings page to WordPress admin menu.
	 *
	 * @since 1.0.0
	 */
	public function add_settings_page() {
		add_submenu_page(
			'edit.php?post_type=wc_product_slider',
			__( 'Settings', 'woocommerce-product-slider' ),
			__( 'Settings', 'woocommerce-product-slider' ),
			'manage_options',
			'wc-product-slider-settings',
			array( $this, 'render_settings_page' )
		);
	}

	/**
	 * Render the settings page.
	 *
	 * @since 1.0.0
	 */
	public function render_settings_page() {
		// Check user permissions.
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		// Handle form submission.
		if ( isset( $_POST['wc_ps_settings_nonce'] ) &&
			wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['wc_ps_settings_nonce'] ) ), 'wc_ps_save_settings' ) ) {
			$this->save_settings();
			echo '<div class="notice notice-success is-dismissible"><p>' . esc_html__( 'Settings saved successfully.', 'woocommerce-product-slider' ) . '</p></div>';
		}

		// Get current settings.
		$default_autoplay = get_option( 'wc_ps_default_autoplay', '1' );
		$default_loop     = get_option( 'wc_ps_default_loop', '1' );
		$default_speed    = get_option( 'wc_ps_default_speed', '3000' );
		?>
		<div class="wrap">
			<h1><?php echo esc_html( get_admin_page_title() ); ?></h1>
			<form method="post" action="">
				<?php wp_nonce_field( 'wc_ps_save_settings', 'wc_ps_settings_nonce' ); ?>
				<table class="form-table">
					<tbody>
						<tr>
							<th scope="row">
								<label for="wc_ps_default_autoplay">
									<?php esc_html_e( 'Default Autoplay', 'woocommerce-product-slider' ); ?>
								</label>
							</th>
							<td>
								<input type="checkbox" name="wc_ps_default_autoplay" id="wc_ps_default_autoplay" value="1" <?php checked( $default_autoplay, '1' ); ?> />
								<p class="description">
									<?php esc_html_e( 'Enable autoplay by default for new sliders.', 'woocommerce-product-slider' ); ?>
								</p>
							</td>
						</tr>
						<tr>
							<th scope="row">
								<label for="wc_ps_default_loop">
									<?php esc_html_e( 'Default Loop', 'woocommerce-product-slider' ); ?>
								</label>
							</th>
							<td>
								<input type="checkbox" name="wc_ps_default_loop" id="wc_ps_default_loop" value="1" <?php checked( $default_loop, '1' ); ?> />
								<p class="description">
									<?php esc_html_e( 'Enable loop by default for new sliders.', 'woocommerce-product-slider' ); ?>
								</p>
							</td>
						</tr>
						<tr>
							<th scope="row">
								<label for="wc_ps_default_speed">
									<?php esc_html_e( 'Default Autoplay Speed (ms)', 'woocommerce-product-slider' ); ?>
								</label>
							</th>
							<td>
								<input type="number" name="wc_ps_default_speed" id="wc_ps_default_speed" value="<?php echo esc_attr( $default_speed ); ?>" min="1000" max="10000" step="100" />
								<p class="description">
									<?php esc_html_e( 'Default autoplay speed in milliseconds for new sliders.', 'woocommerce-product-slider' ); ?>
								</p>
							</td>
						</tr>
					</tbody>
				</table>
				<?php submit_button( __( 'Save Settings', 'woocommerce-product-slider' ) ); ?>
			</form>
		</div>
		<?php
	}

	/**
	 * Save settings.
	 *
	 * @since 1.0.0
	 */
	private function save_settings() {
		// Save default autoplay.
		$default_autoplay = isset( $_POST['wc_ps_default_autoplay'] ) ? '1' : '0';
		update_option( 'wc_ps_default_autoplay', $default_autoplay );

		// Save default loop.
		$default_loop = isset( $_POST['wc_ps_default_loop'] ) ? '1' : '0';
		update_option( 'wc_ps_default_loop', $default_loop );

		// Save default speed.
		if ( isset( $_POST['wc_ps_default_speed'] ) ) {
			$default_speed = absint( $_POST['wc_ps_default_speed'] );
			update_option( 'wc_ps_default_speed', $default_speed );
		}
	}

	/**
	 * Add settings link to plugin list.
	 *
	 * @since 1.0.0
	 * @param array $links Existing plugin action links.
	 * @return array Modified plugin action links.
	 */
	public function add_plugin_action_links( $links ) {
		$settings_link = '<a href="' . esc_url( admin_url( 'edit.php?post_type=wc_product_slider&page=wc-product-slider-settings' ) ) . '">' . __( 'Settings', 'woocommerce-product-slider' ) . '</a>';
		array_unshift( $links, $settings_link );
		return $links;
	}

	/**
	 * Get the plugin name.
	 *
	 * @since  1.0.0
	 * @return string The plugin name.
	 */
	public function get_plugin_name() {
		return $this->plugin_name;
	}

	/**
	 * Get the plugin version.
	 *
	 * @since  1.0.0
	 * @return string The plugin version.
	 */
	public function get_version() {
		return $this->version;
	}
}
